### ISSUE TITLE
Отобразить класс заметок и репозиториев на базу данных

### ISSUE THREAD

**Issue by keder** [keder/todogit#6]
Используя sqlalchemy [docs](https://docs.sqlalchemy.org/en/13/) отобразить [docs-mapper](https://docs.sqlalchemy.org/en/13/orm/mapping_styles.html) объекты репозитория и заметок в объекты базы данных. В качестве базы предлагается на первых порах использовать in-memory-only SQLite database, что в документации используется.

**Comment by danila-terekhov** [comment]
Предлагаю сделать модуль DataBase, в котором будут находится описания  необходимых таблиц и потом посредством одного [маппера](https://ru.wikibooks.org/wiki/SQLAlchemy#%D0%9D%D0%B0%D1%81%D1%82%D1%80%D0%BE%D0%B9%D0%BA%D0%B0_%D0%BE%D1%82%D0%BE%D0%B1%D1%80%D0%B0%D0%B6%D0%B5%D0%BD%D0%B8%D1%8F) отобразить их на бд
